# Generated by Django 4.0.5 on 2022-06-07 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
